# Generated by Django 4.1.4 on 2024-09-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(default='rabab KH.', max_length=50)),
                ('aboutme', models.TextField()),
                ('cvurl', models.CharField(max_length=150)),
                ('whatsappNo', models.IntegerField()),
                ('whatsappLink', models.CharField(max_length=150)),
                ('telegramName', models.CharField(max_length=50)),
                ('telegramLink', models.CharField(max_length=150)),
                ('githubName', models.CharField(max_length=150)),
                ('githubLink', models.CharField(max_length=150)),
                ('linkedInName', models.CharField(max_length=150)),
                ('linkedInlink', models.CharField(max_length=150)),
            ],
        ),
    ]
