# Generated by Django 4.1.4 on 2024-09-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioCode', '0003_skill_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectskill',
        ),
        migrations.CreateModel(
            name='projectSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioCode.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioCode.skill')),
            ],
        ),
    ]
